# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6606dbffb77278413fcaf253a49c9d6bccdf8bf77f5df007f0d146ddb3fa629e0d3fd113684c9dbfb2342f931dee8cdeb0df0ed23455d15ac6477f0bdba613ff

test:
  secret_key_base: 34b8aa7f13bb9056e59c00a14a1364232ca2244c4052eb1688adaad1f131713a2a144ccea787b21f4e30fa17de91ff9cc49abbc11b226a9888763a19bfd4cc6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
